classdef Buttons < robotics.ros.Message
    %Buttons MATLAB implementation of irobotcreate2/Buttons
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'irobotcreate2/Buttons' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '2c6635fea08c0a11307b4518b1f7fd79' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Clean
        Spot
        Dock
        Day
        Hour
        Minute
        Schedule
        Clock
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Clean', 'Clock', 'Day', 'Dock', 'Header', 'Hour', 'Minute', 'Schedule', 'Spot'} % List of non-constant message properties
        ROSPropertyList = {'clean', 'clock', 'day', 'dock', 'header', 'hour', 'minute', 'schedule', 'spot'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Buttons(msg)
            %Buttons Construct the message object Buttons
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'Buttons', 'header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function clean = get.Clean(obj)
            %get.Clean Get the value for property Clean
            clean = logical(obj.JavaMessage.getClean);
        end
        
        function set.Clean(obj, clean)
            %set.Clean Set the value for property Clean
            validateattributes(clean, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'clean');
            
            obj.JavaMessage.setClean(clean);
        end
        
        function spot = get.Spot(obj)
            %get.Spot Get the value for property Spot
            spot = logical(obj.JavaMessage.getSpot);
        end
        
        function set.Spot(obj, spot)
            %set.Spot Set the value for property Spot
            validateattributes(spot, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'spot');
            
            obj.JavaMessage.setSpot(spot);
        end
        
        function dock = get.Dock(obj)
            %get.Dock Get the value for property Dock
            dock = logical(obj.JavaMessage.getDock);
        end
        
        function set.Dock(obj, dock)
            %set.Dock Set the value for property Dock
            validateattributes(dock, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'dock');
            
            obj.JavaMessage.setDock(dock);
        end
        
        function day = get.Day(obj)
            %get.Day Get the value for property Day
            day = logical(obj.JavaMessage.getDay);
        end
        
        function set.Day(obj, day)
            %set.Day Set the value for property Day
            validateattributes(day, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'day');
            
            obj.JavaMessage.setDay(day);
        end
        
        function hour = get.Hour(obj)
            %get.Hour Get the value for property Hour
            hour = logical(obj.JavaMessage.getHour);
        end
        
        function set.Hour(obj, hour)
            %set.Hour Set the value for property Hour
            validateattributes(hour, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'hour');
            
            obj.JavaMessage.setHour(hour);
        end
        
        function minute = get.Minute(obj)
            %get.Minute Get the value for property Minute
            minute = logical(obj.JavaMessage.getMinute);
        end
        
        function set.Minute(obj, minute)
            %set.Minute Set the value for property Minute
            validateattributes(minute, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'minute');
            
            obj.JavaMessage.setMinute(minute);
        end
        
        function schedule = get.Schedule(obj)
            %get.Schedule Get the value for property Schedule
            schedule = logical(obj.JavaMessage.getSchedule);
        end
        
        function set.Schedule(obj, schedule)
            %set.Schedule Set the value for property Schedule
            validateattributes(schedule, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'schedule');
            
            obj.JavaMessage.setSchedule(schedule);
        end
        
        function clock = get.Clock(obj)
            %get.Clock Get the value for property Clock
            clock = logical(obj.JavaMessage.getClock);
        end
        
        function set.Clock(obj, clock)
            %set.Clock Set the value for property Clock
            validateattributes(clock, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'Buttons', 'clock');
            
            obj.JavaMessage.setClock(clock);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Clean = obj.Clean;
            cpObj.Spot = obj.Spot;
            cpObj.Dock = obj.Dock;
            cpObj.Day = obj.Day;
            cpObj.Hour = obj.Hour;
            cpObj.Minute = obj.Minute;
            cpObj.Schedule = obj.Schedule;
            cpObj.Clock = obj.Clock;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Clean = strObj.Clean;
            obj.Spot = strObj.Spot;
            obj.Dock = strObj.Dock;
            obj.Day = strObj.Day;
            obj.Hour = strObj.Hour;
            obj.Minute = strObj.Minute;
            obj.Schedule = strObj.Schedule;
            obj.Clock = strObj.Clock;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Clean = obj.Clean;
            strObj.Spot = obj.Spot;
            strObj.Dock = obj.Dock;
            strObj.Day = obj.Day;
            strObj.Hour = obj.Hour;
            strObj.Minute = obj.Minute;
            strObj.Schedule = obj.Schedule;
            strObj.Clock = obj.Clock;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.irobotcreate2.Buttons.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.irobotcreate2.Buttons;
            obj.reload(strObj);
        end
    end
end
