classdef Note < robotics.ros.Message
    %Note MATLAB implementation of irobotcreate2/Note
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'irobotcreate2/Note' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4d9b44801be38c06e26bc85d74c2792b' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Note_
        Length
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Length', 'Note_'} % List of non-constant message properties
        ROSPropertyList = {'length', 'note'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Note(msg)
            %Note Construct the message object Note
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function note_ = get.Note_(obj)
            %get.Note_ Get the value for property Note_
            note_ = typecast(int8(obj.JavaMessage.getNote), 'uint8');
        end
        
        function set.Note_(obj, note_)
            %set.Note_ Set the value for property Note_
            validateattributes(note_, {'numeric'}, {'nonempty', 'scalar'}, 'Note', 'note_');
            
            obj.JavaMessage.setNote(note_);
        end
        
        function length = get.Length(obj)
            %get.Length Get the value for property Length
            length = typecast(int8(obj.JavaMessage.getLength), 'uint8');
        end
        
        function set.Length(obj, length)
            %set.Length Set the value for property Length
            validateattributes(length, {'numeric'}, {'nonempty', 'scalar'}, 'Note', 'length');
            
            obj.JavaMessage.setLength(length);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Note_ = obj.Note_;
            cpObj.Length = obj.Length;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Note_ = strObj.Note_;
            obj.Length = strObj.Length;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Note_ = obj.Note_;
            strObj.Length = obj.Length;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.irobotcreate2.Note.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.irobotcreate2.Note;
            obj.reload(strObj);
        end
    end
end
