classdef Song < robotics.ros.Message
    %Song MATLAB implementation of irobotcreate2/Song
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'irobotcreate2/Song' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '2a8e64bdbdd926225694c88b701e505f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        Irobotcreate2NoteClass = robotics.ros.msg.internal.MessageFactory.getClassForType('irobotcreate2/Note') % Dispatch to MATLAB class for message type irobotcreate2/Note
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        SongNumber
        Notes
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Notes', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'Notes', 'SongNumber'} % List of non-constant message properties
        ROSPropertyList = {'header', 'notes', 'song_number'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Song(msg)
            %Song Construct the message object Song
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'Song', 'header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function songnumber = get.SongNumber(obj)
            %get.SongNumber Get the value for property SongNumber
            songnumber = typecast(int8(obj.JavaMessage.getSongNumber), 'uint8');
        end
        
        function set.SongNumber(obj, songnumber)
            %set.SongNumber Set the value for property SongNumber
            validateattributes(songnumber, {'numeric'}, {'nonempty', 'scalar'}, 'Song', 'songnumber');
            
            obj.JavaMessage.setSongNumber(songnumber);
        end
        
        function notes = get.Notes(obj)
            %get.Notes Get the value for property Notes
            if isempty(obj.Cache.Notes)
                javaArray = obj.JavaMessage.getNotes;
                array = obj.readJavaArray(javaArray, obj.Irobotcreate2NoteClass);
                obj.Cache.Notes = feval(obj.Irobotcreate2NoteClass, array);
            end
            notes = obj.Cache.Notes;
        end
        
        function set.Notes(obj, notes)
            %set.Notes Set the value for property Notes
            if ~isvector(notes) && isempty(notes)
                % Allow empty [] input
                notes = feval([obj.Irobotcreate2NoteClass '.empty'], 0, 1);
            end
            
            validateattributes(notes, {obj.Irobotcreate2NoteClass}, {'vector'}, 'Song', 'notes');
            
            javaArray = obj.JavaMessage.getNotes;
            array = obj.writeJavaArray(notes, javaArray, obj.Irobotcreate2NoteClass);
            obj.JavaMessage.setNotes(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Notes)
                obj.Cache.Notes = [];
                obj.Cache.Notes = obj.Notes;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Notes = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.SongNumber = obj.SongNumber;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Notes = copy(obj.Notes);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.SongNumber = strObj.SongNumber;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            NotesCell = arrayfun(@(x) feval([obj.Irobotcreate2NoteClass '.loadobj'], x), strObj.Notes, 'UniformOutput', false);
            obj.Notes = vertcat(NotesCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.SongNumber = obj.SongNumber;
            strObj.Header = saveobj(obj.Header);
            strObj.Notes = arrayfun(@(x) saveobj(x), obj.Notes);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.irobotcreate2.Song.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.irobotcreate2.Song;
            obj.reload(strObj);
        end
    end
end
